steps:
  - label: "AMDGPU - Julia 1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      rocm: "*"
      rocmgpu: "*"
    if: build.message !~ /\[skip tests\]/
    command: "julia --project -e 'using Pkg; Pkg.update()'"
    timeout_in_minutes: 20
    env:
      JULIA_NUM_THREADS: 4
      NNOP_TEST_AMDGPU: true

  - label: "CUDA - Julia 1.12"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.12"
      - JuliaCI/julia-test#v1:
      - JuliaCI/julia-coverage#v1:
          codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
    if: build.message !~ /\[skip tests\]/
    command: "julia --project -e 'using Pkg; Pkg.update()'"
    timeout_in_minutes: 20
    env:
      JULIA_NUM_THREADS: 4
      NNOP_TEST_CUDA: true
